controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - base_to_bottom_joint
      - bottom_joint_to_bottom_arm
      - bottom_arm_to_middle_joint
      - middle_joint_to_middle_arm
      - middle_arm_to_upper_joint
      - upper_joint_to_upper_arm
      - upper_arm_to_grabber_joint
      - grabber_joint_to_grabber_arm
      - grabber_arm_to_grabber_piston
      - grabber_piston_to_grabber_hand
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - grabber_hand_to_finger1
      - grabber_hand_to_finger2
      - grabber_hand_to_finger3
initial:  # Define initial robot poses per group
  - group: arm
    pose: start
  - group: hand
    pose: close_hand