arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - base_to_bottom_joint
    - bottom_joint_to_bottom_arm
    - bottom_arm_to_middle_joint
    - middle_joint_to_middle_arm
    - middle_arm_to_upper_joint
    - upper_joint_to_upper_arm
    - upper_arm_to_grabber_joint
    - grabber_joint_to_grabber_arm
    - grabber_arm_to_grabber_piston
    - grabber_piston_to_grabber_hand
  gains:
    base_to_bottom_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    bottom_joint_to_bottom_arm:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    bottom_arm_to_middle_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    middle_joint_to_middle_arm:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    middle_arm_to_upper_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    upper_joint_to_upper_arm:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    upper_arm_to_grabber_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    grabber_joint_to_grabber_arm:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    grabber_arm_to_grabber_piston:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    grabber_piston_to_grabber_hand:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
hand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - grabber_hand_to_finger1
    - grabber_hand_to_finger2
    - grabber_hand_to_finger3
  gains:
    grabber_hand_to_finger1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    grabber_hand_to_finger2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    grabber_hand_to_finger3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1