controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - base_to_bottom_joint
      - bottom_joint_to_bottom_arm
      - bottom_arm_to_middle_joint
      - middle_joint_to_middle_arm
      - middle_arm_to_upper_joint
      - upper_joint_to_upper_arm
      - upper_arm_to_grabber_joint
      - grabber_joint_to_grabber_arm
      - grabber_arm_to_grabber_piston
      - grabber_piston_to_grabber_hand
  - name: hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - grabber_hand_to_finger1
      - grabber_hand_to_finger2
      - grabber_hand_to_finger3